routes/admin.php
<?php

Route::get('/', 'Admin\DashboardController@index')->name('dashboard');

Route::name('profile.')->prefix('profile')->group(function () {
	Route::any('/update', 'Admin\AdminProfileController@update')->name('update');
	Route::any('/changepass', 'Admin\AdminProfileController@changePass')->name('changepass');
});

Route::name('dashboard.')->prefix('dashboard')->group(function () {
	Route::any('/', 'Admin\DashboardController@index')->name('index');
});

Route::name('staff.')->prefix('staff')->group(function () {
	Route::get('/', 'Admin\AdminStaffController@index')->name('index');
	Route::any('/add/{id?}', 'Admin\AdminStaffController@add')->name('add')->where('id', '[0-9]+');
	Route::post('/status', 'Admin\AdminStaffController@status')->name('status');
	Route::any('/delete/{id}', 'Admin\AdminStaffController@delete')->name('delete')->where('id', '[0-9]+');
	Route::any('/fake_login/{id}', 'Admin\AdminStaffController@fake_login')->name('fake_login')->where('id', '[0-9]+');
});

Route::name('category.')->prefix('category')->group(function () {
	Route::get('/', 'Admin\AdminCategoryController@index')->name('list');
	Route::any('/add/{id?}', 'Admin\AdminCategoryController@add')->name('add')->where('id', '[0-9]+');
	Route::any('/status', 'Admin\AdminCategoryController@status')->name('status');
	Route::any('/delete', 'Admin\AdminCategoryController@delete')->name('delete');
});

Route::name('news.')->prefix('news')->group(function () {
	Route::get('/', 'Admin\AdminNewsController@index')->name('index');
	Route::any('/add/{id?}', 'Admin\AdminNewsController@add')->name('add')->where('id', '[0-9]+');
	Route::post('/status', 'Admin\AdminNewsController@status')->name('status');
	Route::get('/delete/{id}', 'Admin\AdminNewsController@delete')->name('delete');

	Route::any('/category', 'Admin\AdminNewsController@category')->name('category');
	Route::any('/category-add/{id?}', 'Admin\AdminNewsController@categoryAdd')->name('category_add')->where('id', '[0-9]+');
	Route::post('/category-status', 'Admin\AdminNewsController@categoryStatus')->name('category_status');
	Route::any('/tags', 'Admin\AdminNewsController@tags')->name('tags');
	Route::any('/tags-add', 'Admin\AdminNewsController@tags-add')->name('tags_add');
});

Route::name('static.')->prefix('static')->group(function () {
	Route::get('/', 'Admin\AdminStaticsController@index')->name('index');
	Route::any('/add/{id?}', 'Admin\AdminStaticsController@add')->name('add')->where('id', '[0-9]+');
	Route::post('/status', 'Admin\AdminStaticsController@status')->name('status');
	Route::get('/delete/{id}', 'Admin\AdminStaticsController@delete')->name('delete');
	Route::any('/category', 'Admin\AdminStaticsController@category')->name('category');
	Route::any('/category-add/{id?}', 'Admin\AdminStaticsController@categoryAdd')->name('category_add')->where('id', '[0-9]+');
	Route::post('/category-status', 'Admin\AdminStaticsController@categoryStatus')->name('category_status');
});

Route::name('event.')->prefix('event')->group(function () {
	Route::get('/', 'Admin\AdminEventsController@index')->name('index');
	Route::any('/add/{id?}', 'Admin\AdminEventsController@add')->name('add')->where('id', '[0-9]+');
	Route::post('/status', 'Admin\AdminEventsController@status')->name('status');
	Route::get('/delete/{id}', 'Admin\AdminEventsController@delete')->name('delete')->where('id', '[0-9]+');

	Route::any('/category', 'Admin\AdminEventsController@category')->name('category');
	Route::any('/category-add/{id?}', 'Admin\AdminEventsController@categoryAdd')->name('category_add')->where('id', '[0-9]+');
	Route::post('/category-status', 'Admin\AdminEventsController@categoryStatus')->name('category_status');
});

Route::name('view.')->prefix('view')->group(function () {
	Route::get('/menu', 'Admin\AdminMenuController@index')->name('menu');
	Route::any('/menu_add/{id?}', 'Admin\AdminMenuController@add')->name('menu_add')->where('id', '[0-9]+');
	Route::any('/menu_delete/{id?}', 'Admin\AdminmenuController@delete')->name('menu_delete')->where('id', '[0-9]+');
	Route::post('/menu-status', 'Admin\AdminMenuController@status')->name('menu_status');

	Route::get('/banner', 'Admin\AdminBannerController@index')->name('banner');
	Route::any('/banner_add/{id?}', 'Admin\AdminBannerController@add')->name('banner_add')->where('id', '[0-9]+');
	Route::any('/banner_delete/{id?}', 'Admin\AdminBannerController@delete')->name('banner_delete')->where('id', '[0-9]+');
	Route::post('/banner-status', 'Admin\AdminBannerController@status')->name('banner_status');

	Route::get('/partner', 'Admin\AdminPartnerController@index')->name('partner');
	Route::any('/partner_add/{id?}', 'Admin\AdminPartnerController@add')->name('partner_add')->where('id', '[0-9]+');
	Route::any('/partner_delete/{id?}', 'Admin\AdminPartnerController@delete')->name('partner_delete')->where('id', '[0-9]+');
	Route::post('/partner-status', 'Admin\AdminPartnerController@status')->name('partner_status');

	Route::get('/achievement', 'Admin\AdminAchievementController@index')->name('achievement');
	Route::any('/achievement_add/{id?}', 'Admin\AdminAchievementController@add')->name('achievement_add')->where('id', '[0-9]+');
	Route::any('/achievement_delete/{id?}', 'Admin\AdminAchievementController@delete')->name('achievement_delete')->where('id', '[0-9]+');
	Route::post('/achievement-status', 'Admin\AdminAchievementController@status')->name('achievement_status');

	Route::get('/service', 'Admin\AdminServiceController@index')->name('service');
	Route::any('/service_add/{id?}', 'Admin\AdminServiceController@add')->name('service_add')->where('id', '[0-9]+');
	Route::any('/service_delete/{id?}', 'Admin\AdminServiceController@delete')->name('service_delete')->where('id', '[0-9]+');
	Route::post('/service-status', 'Admin\AdminServiceController@status')->name('service_status');

	Route::get('/opinion', 'Admin\AdminOpinionController@index')->name('opinion');
	Route::any('/opinion_add/{id?}', 'Admin\AdminOpinionController@add')->name('opinion_add')->where('id', '[0-9]+');
	Route::any('/opinion_delete/{id?}', 'Admin\AdminOpinionController@delete')->name('opinion_delete')->where('id', '[0-9]+');
	Route::post('/opinion-status', 'Admin\AdminOpinionController@status')->name('opinion_status');
});

Route::name('other.')->prefix('other')->group(function () {
	Route::get('/founder', 'Admin\AdminFounderController@index')->name('founder');
	Route::any('/founder_add/{id?}', 'Admin\AdminFounderController@add')->name('founder_add')->where('id', '[0-9]+');
	Route::any('/founder_delete/{id?}', 'Admin\AdminfounderController@delete')->name('founder_delete')->where('id', '[0-9]+');
	Route::post('/founder_status', 'Admin\AdminFounderController@status')->name('founder_status');

	Route::get('/enterprice_network', 'Admin\AdminEnterpriceNetworkController@index')->name('enterprice_network');
	Route::any('/enterprice_network_add/{id?}', 'Admin\AdminEnterpriceNetworkController@add')->name('enterprice_network_add')->where('id', '[0-9]+');
	Route::any('/enterprice_network_delete/{id?}', 'Admin\AdminenterpriceController@delete')->name('enterprice_network_delete')->where('id', '[0-9]+');
	Route::post('/enterprice_network-status', 'Admin\AdminEnterpriceNetworkController@status')->name('enterprice_network_status');

	Route::get('/contact', 'Admin\AdminContactController@index')->name('contact');
	Route::any('/detail/{id?}', 'Admin\AdminContactController@detail')->name('detail')->where('id', '[0-9]+');
	Route::any('/contact_delete/{id?}', 'Admin\AdminContactController@delete')->name('contact_delete')->where('id', '[0-9]+');
	Route::post('/contact-status', 'Admin\AdminContactController@status')->name('contact_status');
});

Route::name('configs.')->prefix('configs')->group(function () {
	Route::any('/', 'Admin\AdminConfigurationController@index')->name('configuration');
	Route::any('/introduce', 'Admin\AdminConfigurationIntroduceController@index')->name('introduce');
	Route::any('/about', 'Admin\AdminConfigurationAboutController@index')->name('about');
	Route::any('/certification', 'Admin\AdminConfigurationCertificationController@index')->name('certification');
	Route::any('/gears', 'Admin\AdminConfigurationGearsController@index')->name('gears');
	Route::any('/member', 'Admin\AdminConfigurationMemberController@index')->name('member');
	Route::any('/user-translate', 'Admin\AdminUserTranslateController@index')->name('user_translate');
	Route::any('/user-translate/add', 'Admin\AdminUserTranslateController@add')->name('user_translate_add');

	Route::get('/step', 'Admin\AdminItemStepController@index')->name('step');
	Route::any('/step_add/{id?}', 'Admin\AdminItemStepController@add')->name('step_add')->where('id', '[0-9]+');
	Route::any('/step_delete/{id?}', 'Admin\AdminItemStepController@delete')->name('step_delete')->where('id', '[0-9]+');
	Route::post('/step-status', 'Admin\AdminItemStepController@status')->name('step_status');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::name('auth_admin.')->prefix('auth_admin')->group(function () {
   	Route::any('/login', 'Auth\AdminAuthenController@doLogin')->name('login');
   // Route::any('/login', 'Auth\AdminAuthenController@doLogin')->name('do_login');
    Route::get('/logout', 'Auth\AdminAuthenController@doLogout')->name('do_logout');
});

Route::get('access-denied', function () {
	echo 'Access Denied !';
})->name('access_denied');
Route::get('/index', 'Page\GoogleAnalyticController@index');
Route::get('phpinfo', function () {
	echo phpinfo();
})->name('access_denied');

Route::name('admin.')->prefix('admin')->middleware('auth.admin')->group(function () {
	require_once 'admin.php';
});

Route::name('authen.')->prefix('authen')->group(function () {
   Route::any('/login', 'Auth\UserAuthenController@login')->name('login');
   Route::get('/logout', 'Auth\UserAuthenController@logout')->name('logout');
    Route::any('/register', 'UserController@register')->name('register');
});

Route::name('user.')->prefix('user')->middleware('auth.user')->group(function () {
	Route::name('profile.')->prefix('profile')->group(function () {
		Route::any('/changepass', 'UserController@changePass')->name('changepass');
	});
});
//Route::get('add-news', 'Page\PageController@addNews')->name('add-news');
Route::group([
        'middleware' => ['setLocale']
    ], function () {
        Route::get('/', 'Page\HomeController@index')->name('index');
        Route::get('/tin-tuc', 'Page\NewsController@index')->name('news');
        Route::get('/{cat_name_rewrite}/{id}', 'Page\NewsController@category')->name('cat-news')->where('id', '[0-9]+');
        Route::get('/tin-tuc/{new_rewrite}/{id}', 'Page\NewsController@detail')->name('news_detail');
        Route::get('/dich-vu', 'Page\ServiceController@index')->name('news');
        Route::get('/dich-vu/{ser_name_rewrite}/{id}', 'Page\ServiceController@detail')->name('news-detail');

        Route::get('/gioi-thieu', 'Page\AboutController@about')->name('about');
        Route::get('/cac-sang-lap-vien', 'Page\AboutController@founder')->name('founder');
        Route::get('/cac-mang-luoi-doanh-nghiep-vung', 'Page\AboutController@memberNetwork')->name('member-network');
        Route::get('/tham-gia-mang-luoi', 'Page\AboutController@joinNetwork')->name('join-network');
        Route::get('/doi-ngu', 'Page\AboutController@team')->name('team');
        Route::get('/doi-tac', 'Page\AboutController@partner')->name('partner');
        Route::get('/ghi-nhan-cua-khach-hang-doi-tac', 'Page\AboutController@comments')->name('comments');

        Route::get('/danh-gia-binh-dang-gioi', 'Page\ServiceController@gear')->name('gear');

        Route::get('/chung-chi-edge', 'Page\ServiceController@edge')->name('edge');
        Route::get('/tu-van-doanh-nghiep', 'Page\ServiceController@tuvan')->name('tu-van');
        Route::get('/khoa-dao-tao-doanh-nghiep', 'Page\ServiceController@course')->name('course');

        Route::get('/lien-he', 'Page\ContactController@contactPage')->name('contact-page');
        Route::get('/tim-kiem', 'Page\SearchController@search')->name('search');
        Route::get('/thu-vien', 'Page\AlbumController@index')->name('album');
        Route::get('/thu-vien/{ban_name_rewrite}/{id}', 'Page\AlbumController@albumDetail')->name('album-detail');

        Route::get('/thu-vien/videos', 'Page\AlbumController@videos')->name('videos');

        Route::get('/hoat-dong-su-kien/su-kien-sap-dien-ra', 'Page\EventController@upcomingEvent')->name('upcoming');
        Route::get('/hoat-dong-su-kien/su-kien-da-dien-ra', 'Page\EventController@previousEvent')->name('previous');
        Route::get('/hoat-dong-su-kien/chien-dich', 'Page\EventController@campaign')->name('campaigns');
        Route::get('/hoat-dong-su-kien/ban-cam-ket-vi-bdg-vn', 'Page\EventController@pledge')->name('pledge');

//        Route::get('/kien-thuc-tham-khao/', 'Page\StaticController@index')->name('hub-index');
        Route::get('/kien-thuc-tham-khao/{cat_name_rewrite}/{id}', 'Page\StaticController@category')->name('hub-cate');
        Route::get('/kien-thuc-tham-khao/{cat_name_rewrite}/{sta_name_rewrite}/{id}', 'Page\StaticController@detail')->name('hub-detail');

        Route::post('/contact', 'Page\ContactController@contact')->name('contact');
        Route::post('/contact-event', 'Page\ContactController@contactEvent')->name('contact-event');
        Route::post('/register-event', 'Page\ContactController@contactEventRegister')->name('register-event-form');
        Route::post('/contact-story', 'Page\ContactController@contactStory')->name('contact-story');
        Route::post('/contact-form', 'Page\ContactController@contactForm')->name('contact-form');

        Route::get('/dang-ky-tham-gia', 'Page\ContactController@joinRegister')->name('join-register');
        Route::get('/dang-ky-su-kien', 'Page\ContactController@registerEvent')->name('register-event');
        Route::get('/dang-ky-tai-bao-cao', 'Page\ContactController@registerReport')->name('register-report');

        Route::post('/contact-join', 'Page\ContactController@contactJoin')->name('contact-join');

        Route::get('/{lang?}', 'Page\PageController@lang')->name('lang');
    });

Route::name('services.')->prefix('services')->group(function () {
   Route::name('upload.')->prefix('upload')->group(function () {
		Route::post('/', 'UploadController@upload')->name('upload');
		Route::get('/get', 'UploadController@get')->name('get');
	});
});

app/Models/Events.php
<?php
namespace App\Models;
use App\Models\Model;

class Events extends Model
{

	protected $table			= 'events';
	protected $primaryKey		= 'eve_id';
	protected $guarded			= ['eve_isadmin'];
	//protected $fillable		= [];
	public $timestamps			= false;
	public $prefix				= 'eve_';
	public $defaultFieldsSelect	= ['eve_id', 'eve_title', 'eve_category_id'];

	const FIELD_FOR_DEFAULT		= ['eve_id', 'eve_title', 'eve_category_id'];
	const KEY_PRODUCT			= 'eve_id';
	const KEY_CATEGORY			= 'eve_category_id';

	/* RELATION SHIP FUNCTION */
	public function category(){
		return $this->hasOne(
			\App\Models\Category::class,
			'cat_id',
			static::KEY_CATEGORY
		)->where('cat_type', '=', 'event')->select(\App\Models\Category::FIELD_FOR_DEFAULT);
	}
}
?>

resources/views/admin/event/category_list.blade.php
@extends('admin.layouts')
@section('CONTAINER')
<div class="br-pageheader">
    <nav class="breadcrumb pd-0 mg-0 tx-12">
      <a class="breadcrumb-item" href="{{route('admin.event.index')}}">Sự kiện</a>
      <a class="breadcrumb-item" href="{{route('admin.event.category')}}">Danh mục</a>
      <span class="breadcrumb-item active">Danh sách</span>
    </nav>
</div>
<div class="br-pagetitle" style="justify-content: space-between;">
	<h4>Danh sách danh mục</h4>
	<div class=""><a href="{{ route('admin.event.category_add') }}" class="btn btn-info">Thêm mới</a></div>
</div>

<div class="br-pagebody">
	<section class="listing-container">
        <div class="br-section-wrapper container-fluid">
			<h6 class="br-section-label">Tìm kiếm</h6>
  	  		<form method="GET" action="">
  	  			<div class="row">
		            <div class="col-lg-3">
		              <input class="form-control" name="name" placeholder="Tên danh mục" type="text" value="{{ isset($dataSearch['name']) ? $dataSearch['name'] : '' }}">
		            </div>
		            <div class="col-lg-2 mg-t-10 mg-lg-t-0">
		            	<button class="btn btn-primary btn-block mg-b-10"><i class="fa fa-send mg-r-10"></i>Search</button>
		            </div>
		        </div>
  	    	</form>


		  	<div class="bd rounded table-responsive">
		  	  	<table class="table table-bordered table-striped mg-b-0">
		  	  		<tbody class="">
		                <tr class="thead-colored thead-light">
				          <td>Tiêu đề</td>
				          <td class="text-center">Thứ tự</td>
				          <td class="text-center">Kích hoạt</td>
				          <td class="text-center">Ngày tạo</td>
				          <td class="text-center">Sửa</td>
				        </tr>

				      	@foreach ($category as $keys => $cate)
					      	<tr>
								<td colspan="8" align="center" style="font-weight: bold; color: #ca1111; font-size: 15px;">{{ $arrType[$keys] }}</td>
							</tr>
							@foreach ($cate as $item)
								<tr id="record_{{ $item->cat_id}}">
						          	<td>
						          		@for ($i = 0; $i < $item['level']; $i++)
										---|
										@endfor
						          		{{ $item->cat_name }}
						          	</td>
						          	<td class="text-center">{{ $item->cat_order }}</td>
						          	<td class="text-center">
										<a href="javascript:;" class="box_active" onclick="changeActive('{{ route('admin.event.category_status')}}', '{{ $item->cat_id }}', 'active')">
											@if($item->cat_active == 1)
												<i class="far fa-check-square" style="font-size: 14px;"></i>
											@else
												<i class="far fa-square" style="font-size: 14px;"></i>
											@endif
										</a>
									</td>
						          	<td class="text-center">{{ date("d/m/y H:i",$item->cat_create_time) }}</td>
						          	<td class="text-center">
						          		<a href="{{ route('admin.event.category_add', ['id' => $item->cat_id])}}" class=""><i class="fas fa-edit"></i> Sửa</a>
						          	</td>
						        </tr>
							@endforeach
				      	@endforeach

		      		</tbody>
		  	  	</table>
            </div>
        </div>
    </section>

</div>
@endsection

resources/views/admin/event/list.blade.php
<?php
use App\Repositories\EventsRepository as Events;
use App\Helper\Upload as UploadHelper;
?>
@extends('admin.layouts')
@section('CONTAINER')

<div class="br-pageheader">
    <nav class="breadcrumb pd-0 mg-0 tx-12">
      <a class="breadcrumb-item" href="{{route('admin.event.index')}}">Sự kiện</a>
      <span class="breadcrumb-item active">Danh sách</span>
    </nav>
</div>
<div class="br-pagetitle" style="justify-content: space-between;">
	<h4>Danh sách Sự kiện</h4>
	<div class=""><a href="{{ route('admin.event.add') }}" class="btn btn-info">Thêm mới</a></div>
</div>
<div class="br-pagebody">
	<section class="listing-container">
        <div class="br-section-wrapper container-fluid">
			<h6 class="br-section-label">Tìm kiếm</h6>
  	  		<form method="GET" action="">
  	  			<div class="row">
		            <div class="col-lg-2">
		              <input class="form-control" name="title" placeholder="Tiêu đề" type="text" value="{{ isset($dataSearch['title']) ? $dataSearch['title'] : '' }}">
		            </div>
		            <div class="col-lg-2 mg-t-10 mg-lg-t-0">
		            	<button class="btn btn-primary btn-block mg-b-10"><i class="fa fa-send mg-r-10"></i>Search</button>
		            </div>
		        </div>
  	    	</form>

		  	<div class="bd rounded table-responsive">
		  	  	<table class="table table-bordered table-striped mg-b-0">
		  	  		<tbody class="">
		                <tr class="thead-colored thead-light">
		                	<td class="wd-5p">STT</td>
		                	<td class="wd-5p">Ảnh</td>
							<td class="wd-10p">Tiêu đề</td>
							<td class="wd-10p">Tiêu đề en</td>
							<td class="wd-10p text-center">Loại sự kiện</td>
							<td class="wd-10p text-center">Ngày tạo</td>
							<td class="wd-10p text-center">Sửa</td>
							<td class="wd-10p text-center">Xóa</td>
		                </tr>
				      	@foreach ($events as $item)
							<tr id="record_{{ $item->eve_id}}">
					          	<td class="text-center">{{ $loop->index + 1 + ($pagination['current_page'] - 1) * $pagination['perpage'] }}</td>
					          	<td>
                                    <img style="max-width: 100px; height: auto" src="{{ UploadHelper::getUrlImage('news', $item->eve_picture) }}" alt="">
                                </td>
					          	<td>{{ $item->eve_title }}</td>
					          	<td>{{ $item->eve_title_en }}</td>
					          	<td class="text-center">
									{{ Events::getStatusLabel($item->eve_new) }}
								</td>
					          	<td class="text-center">{{ date("d/m/y H:i",$item->eve_create_time) }}</td>
					          	<td class="text-center">
					          		<a href="{{ route('admin.event.add', ['id' => $item->eve_id])}}" class=""><i class="fas fa-edit"></i> Sửa</a>
					          	</td>
					          	<td class="text-center">
									<a class="buttonDelteRecord text-danger" href="{{ route('admin.event.delete', ['id' => $item->eve_id]) }}" ><i class="fa fa-times-circle"></i> Xóa</a>
					          	</td>
					        </tr>
				      	@endforeach

		      		</tbody>
		  	  	</table>
		  	</div>

        </div>
    </section>
    @include("admin.pagination")
</div>
@endsection