routes/admin.php
<?php

Route::get('/', 'Admin\DashboardController@index')->name('dashboard');

Route::name('profile.')->prefix('profile')->group(function () {
	Route::any('/update', 'Admin\AdminProfileController@update')->name('update');
	Route::any('/changepass', 'Admin\AdminProfileController@changePass')->name('changepass');
});

Route::name('dashboard.')->prefix('dashboard')->group(function () {
	Route::any('/', 'Admin\DashboardController@index')->name('index');
});

Route::name('staff.')->prefix('staff')->group(function () {
	Route::get('/', 'Admin\AdminStaffController@index')->name('index');
	Route::any('/add/{id?}', 'Admin\AdminStaffController@add')->name('add')->where('id', '[0-9]+');
	Route::post('/status', 'Admin\AdminStaffController@status')->name('status');
	Route::any('/delete/{id}', 'Admin\AdminStaffController@delete')->name('delete')->where('id', '[0-9]+');
	Route::any('/fake_login/{id}', 'Admin\AdminStaffController@fake_login')->name('fake_login')->where('id', '[0-9]+');
});

Route::name('category.')->prefix('category')->group(function () {
	Route::get('/', 'Admin\AdminCategoryController@index')->name('list');
	Route::any('/add/{id?}', 'Admin\AdminCategoryController@add')->name('add')->where('id', '[0-9]+');
	Route::any('/status', 'Admin\AdminCategoryController@status')->name('status');
	Route::any('/delete', 'Admin\AdminCategoryController@delete')->name('delete');
});

Route::name('news.')->prefix('news')->group(function () {
	Route::get('/', 'Admin\AdminNewsController@index')->name('index');
	Route::any('/add/{id?}', 'Admin\AdminNewsController@add')->name('add')->where('id', '[0-9]+');
	Route::post('/status', 'Admin\AdminNewsController@status')->name('status');
	Route::get('/delete/{id}', 'Admin\AdminNewsController@delete')->name('delete');

	Route::any('/category', 'Admin\AdminNewsController@category')->name('category');
	Route::any('/category-add/{id?}', 'Admin\AdminNewsController@categoryAdd')->name('category_add')->where('id', '[0-9]+');
	Route::post('/category-status', 'Admin\AdminNewsController@categoryStatus')->name('category_status');
	Route::any('/tags', 'Admin\AdminNewsController@tags')->name('tags');
	Route::any('/tags-add', 'Admin\AdminNewsController@tags-add')->name('tags_add');
});

Route::name('static.')->prefix('static')->group(function () {
	Route::get('/', 'Admin\AdminStaticsController@index')->name('index');
	Route::any('/add/{id?}', 'Admin\AdminStaticsController@add')->name('add')->where('id', '[0-9]+');
	Route::post('/status', 'Admin\AdminStaticsController@status')->name('status');
	Route::get('/delete/{id}', 'Admin\AdminStaticsController@delete')->name('delete');
	Route::any('/category', 'Admin\AdminStaticsController@category')->name('category');
	Route::any('/category-add/{id?}', 'Admin\AdminStaticsController@categoryAdd')->name('category_add')->where('id', '[0-9]+');
	Route::post('/category-status', 'Admin\AdminStaticsController@categoryStatus')->name('category_status');
});

Route::name('event.')->prefix('event')->group(function () {
	Route::get('/', 'Admin\AdminEventsController@index')->name('index');
	Route::any('/add/{id?}', 'Admin\AdminEventsController@add')->name('add')->where('id', '[0-9]+');
	Route::post('/status', 'Admin\AdminEventsController@status')->name('status');
	Route::get('/delete/{id}', 'Admin\AdminEventsController@delete')->name('delete')->where('id', '[0-9]+');

	Route::any('/category', 'Admin\AdminEventsController@category')->name('category');
	Route::any('/category-add/{id?}', 'Admin\AdminEventsController@categoryAdd')->name('category_add')->where('id', '[0-9]+');
	Route::post('/category-status', 'Admin\AdminEventsController@categoryStatus')->name('category_status');
});

Route::name('view.')->prefix('view')->group(function () {
	Route::get('/menu', 'Admin\AdminMenuController@index')->name('menu');
	Route::any('/menu_add/{id?}', 'Admin\AdminMenuController@add')->name('menu_add')->where('id', '[0-9]+');
	Route::any('/menu_delete/{id?}', 'Admin\AdminmenuController@delete')->name('menu_delete')->where('id', '[0-9]+');
	Route::post('/menu-status', 'Admin\AdminMenuController@status')->name('menu_status');

	Route::get('/banner', 'Admin\AdminBannerController@index')->name('banner');
	Route::any('/banner_add/{id?}', 'Admin\AdminBannerController@add')->name('banner_add')->where('id', '[0-9]+');
	Route::any('/banner_delete/{id?}', 'Admin\AdminBannerController@delete')->name('banner_delete')->where('id', '[0-9]+');
	Route::post('/banner-status', 'Admin\AdminBannerController@status')->name('banner_status');

	Route::get('/partner', 'Admin\AdminPartnerController@index')->name('partner');
	Route::any('/partner_add/{id?}', 'Admin\AdminPartnerController@add')->name('partner_add')->where('id', '[0-9]+');
	Route::any('/partner_delete/{id?}', 'Admin\AdminPartnerController@delete')->name('partner_delete')->where('id', '[0-9]+');
	Route::post('/partner-status', 'Admin\AdminPartnerController@status')->name('partner_status');

	Route::get('/achievement', 'Admin\AdminAchievementController@index')->name('achievement');
	Route::any('/achievement_add/{id?}', 'Admin\AdminAchievementController@add')->name('achievement_add')->where('id', '[0-9]+');
	Route::any('/achievement_delete/{id?}', 'Admin\AdminAchievementController@delete')->name('achievement_delete')->where('id', '[0-9]+');
	Route::post('/achievement-status', 'Admin\AdminAchievementController@status')->name('achievement_status');

	Route::get('/service', 'Admin\AdminServiceController@index')->name('service');
	Route::any('/service_add/{id?}', 'Admin\AdminServiceController@add')->name('service_add')->where('id', '[0-9]+');
	Route::any('/service_delete/{id?}', 'Admin\AdminServiceController@delete')->name('service_delete')->where('id', '[0-9]+');
	Route::post('/service-status', 'Admin\AdminServiceController@status')->name('service_status');

	Route::get('/opinion', 'Admin\AdminOpinionController@index')->name('opinion');
	Route::any('/opinion_add/{id?}', 'Admin\AdminOpinionController@add')->name('opinion_add')->where('id', '[0-9]+');
	Route::any('/opinion_delete/{id?}', 'Admin\AdminOpinionController@delete')->name('opinion_delete')->where('id', '[0-9]+');
	Route::post('/opinion-status', 'Admin\AdminOpinionController@status')->name('opinion_status');
});

Route::name('other.')->prefix('other')->group(function () {
	Route::get('/founder', 'Admin\AdminFounderController@index')->name('founder');
	Route::any('/founder_add/{id?}', 'Admin\AdminFounderController@add')->name('founder_add')->where('id', '[0-9]+');
	Route::any('/founder_delete/{id?}', 'Admin\AdminfounderController@delete')->name('founder_delete')->where('id', '[0-9]+');
	Route::post('/founder_status', 'Admin\AdminFounderController@status')->name('founder_status');

	Route::get('/enterprice_network', 'Admin\AdminEnterpriceNetworkController@index')->name('enterprice_network');
	Route::any('/enterprice_network_add/{id?}', 'Admin\AdminEnterpriceNetworkController@add')->name('enterprice_network_add')->where('id', '[0-9]+');
	Route::any('/enterprice_network_delete/{id?}', 'Admin\AdminenterpriceController@delete')->name('enterprice_network_delete')->where('id', '[0-9]+');
	Route::post('/enterprice_network-status', 'Admin\AdminEnterpriceNetworkController@status')->name('enterprice_network_status');

	Route::get('/contact', 'Admin\AdminContactController@index')->name('contact');
	Route::any('/detail/{id?}', 'Admin\AdminContactController@detail')->name('detail')->where('id', '[0-9]+');
	Route::any('/contact_delete/{id?}', 'Admin\AdminContactController@delete')->name('contact_delete')->where('id', '[0-9]+');
	Route::post('/contact-status', 'Admin\AdminContactController@status')->name('contact_status');
});

Route::name('configs.')->prefix('configs')->group(function () {
	Route::any('/', 'Admin\AdminConfigurationController@index')->name('configuration');
	Route::any('/introduce', 'Admin\AdminConfigurationIntroduceController@index')->name('introduce');
	Route::any('/about', 'Admin\AdminConfigurationAboutController@index')->name('about');
	Route::any('/certification', 'Admin\AdminConfigurationCertificationController@index')->name('certification');
	Route::any('/gears', 'Admin\AdminConfigurationGearsController@index')->name('gears');
	Route::any('/member', 'Admin\AdminConfigurationMemberController@index')->name('member');
	Route::any('/user-translate', 'Admin\AdminUserTranslateController@index')->name('user_translate');
	Route::any('/user-translate/add', 'Admin\AdminUserTranslateController@add')->name('user_translate_add');

	Route::get('/step', 'Admin\AdminItemStepController@index')->name('step');
	Route::any('/step_add/{id?}', 'Admin\AdminItemStepController@add')->name('step_add')->where('id', '[0-9]+');
	Route::any('/step_delete/{id?}', 'Admin\AdminItemStepController@delete')->name('step_delete')->where('id', '[0-9]+');
	Route::post('/step-status', 'Admin\AdminItemStepController@status')->name('step_status');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::name('auth_admin.')->prefix('auth_admin')->group(function () {
   	Route::any('/login', 'Auth\AdminAuthenController@doLogin')->name('login');
   // Route::any('/login', 'Auth\AdminAuthenController@doLogin')->name('do_login');
    Route::get('/logout', 'Auth\AdminAuthenController@doLogout')->name('do_logout');
});

Route::get('access-denied', function () {
	echo 'Access Denied !';
})->name('access_denied');
Route::get('/index', 'Page\GoogleAnalyticController@index');
Route::get('phpinfo', function () {
	echo phpinfo();
})->name('access_denied');

Route::name('admin.')->prefix('admin')->middleware('auth.admin')->group(function () {
	require_once 'admin.php';
});

Route::name('authen.')->prefix('authen')->group(function () {
   Route::any('/login', 'Auth\UserAuthenController@login')->name('login');
   Route::get('/logout', 'Auth\UserAuthenController@logout')->name('logout');
    Route::any('/register', 'UserController@register')->name('register');
});

Route::name('user.')->prefix('user')->middleware('auth.user')->group(function () {
	Route::name('profile.')->prefix('profile')->group(function () {
		Route::any('/changepass', 'UserController@changePass')->name('changepass');
	});
});
//Route::get('add-news', 'Page\PageController@addNews')->name('add-news');
Route::group([
        'middleware' => ['setLocale']
    ], function () {
        Route::get('/', 'Page\HomeController@index')->name('index');
        Route::get('/tin-tuc', 'Page\NewsController@index')->name('news');
        Route::get('/{cat_name_rewrite}/{id}', 'Page\NewsController@category')->name('cat-news')->where('id', '[0-9]+');
        Route::get('/tin-tuc/{new_rewrite}/{id}', 'Page\NewsController@detail')->name('news_detail');
        Route::get('/dich-vu', 'Page\ServiceController@index')->name('news');
        Route::get('/dich-vu/{ser_name_rewrite}/{id}', 'Page\ServiceController@detail')->name('news-detail');

        Route::get('/gioi-thieu', 'Page\AboutController@about')->name('about');
        Route::get('/cac-sang-lap-vien', 'Page\AboutController@founder')->name('founder');
        Route::get('/cac-mang-luoi-doanh-nghiep-vung', 'Page\AboutController@memberNetwork')->name('member-network');
        Route::get('/tham-gia-mang-luoi', 'Page\AboutController@joinNetwork')->name('join-network');
        Route::get('/doi-ngu', 'Page\AboutController@team')->name('team');
        Route::get('/doi-tac', 'Page\AboutController@partner')->name('partner');
        Route::get('/ghi-nhan-cua-khach-hang-doi-tac', 'Page\AboutController@comments')->name('comments');

        Route::get('/danh-gia-binh-dang-gioi', 'Page\ServiceController@gear')->name('gear');

        Route::get('/chung-chi-edge', 'Page\ServiceController@edge')->name('edge');
        Route::get('/tu-van-doanh-nghiep', 'Page\ServiceController@tuvan')->name('tu-van');
        Route::get('/khoa-dao-tao-doanh-nghiep', 'Page\ServiceController@course')->name('course');

        Route::get('/lien-he', 'Page\ContactController@contactPage')->name('contact-page');
        Route::get('/tim-kiem', 'Page\SearchController@search')->name('search');
        Route::get('/thu-vien', 'Page\AlbumController@index')->name('album');
        Route::get('/thu-vien/{ban_name_rewrite}/{id}', 'Page\AlbumController@albumDetail')->name('album-detail');

        Route::get('/thu-vien/videos', 'Page\AlbumController@videos')->name('videos');

        Route::get('/hoat-dong-su-kien/su-kien-sap-dien-ra', 'Page\EventController@upcomingEvent')->name('upcoming');
        Route::get('/hoat-dong-su-kien/su-kien-da-dien-ra', 'Page\EventController@previousEvent')->name('previous');
        Route::get('/hoat-dong-su-kien/chien-dich', 'Page\EventController@campaign')->name('campaigns');
        Route::get('/hoat-dong-su-kien/ban-cam-ket-vi-bdg-vn', 'Page\EventController@pledge')->name('pledge');

//        Route::get('/kien-thuc-tham-khao/', 'Page\StaticController@index')->name('hub-index');
        Route::get('/kien-thuc-tham-khao/{cat_name_rewrite}/{id}', 'Page\StaticController@category')->name('hub-cate');
        Route::get('/kien-thuc-tham-khao/{cat_name_rewrite}/{sta_name_rewrite}/{id}', 'Page\StaticController@detail')->name('hub-detail');

        Route::post('/contact', 'Page\ContactController@contact')->name('contact');
        Route::post('/contact-event', 'Page\ContactController@contactEvent')->name('contact-event');
        Route::post('/register-event', 'Page\ContactController@contactEventRegister')->name('register-event-form');
        Route::post('/contact-story', 'Page\ContactController@contactStory')->name('contact-story');
        Route::post('/contact-form', 'Page\ContactController@contactForm')->name('contact-form');

        Route::get('/dang-ky-tham-gia', 'Page\ContactController@joinRegister')->name('join-register');
        Route::get('/dang-ky-su-kien', 'Page\ContactController@registerEvent')->name('register-event');
        Route::get('/dang-ky-tai-bao-cao', 'Page\ContactController@registerReport')->name('register-report');

        Route::post('/contact-join', 'Page\ContactController@contactJoin')->name('contact-join');

        Route::get('/{lang?}', 'Page\PageController@lang')->name('lang');
    });

Route::name('services.')->prefix('services')->group(function () {
   Route::name('upload.')->prefix('upload')->group(function () {
		Route::post('/', 'UploadController@upload')->name('upload');
		Route::get('/get', 'UploadController@get')->name('get');
	});
});

resources/views/admin/error.blade.php
@if($errors)
	<div class="alert alert-danger">
	  	<ul>
	      @foreach ($errors as $error)
	          <li>{{ $error }}</li>
	      @endforeach
	  	</ul>
	</div>
@endif

resources/views/admin/flash-message.blade.php
@if (Session::has('success'))
    <script type="text/javascript"> $.growl.notice({message: "{{ Session::get('success') }}"}); </script>
@endif
@if (Session::has('error'))
    <script type="text/javascript"> $.growl.error({message: "{{ Session::get('error') }}"}); </script>
@endif
@if (Session::has('warning'))
    <script type="text/javascript"> $.growl.warning({message: "{{ Session::get('warning') }}"}); </script>
@endif

resources/views/admin/header.blade.php
<div class="br-header">
      <div class="br-header-left">
        <div class="navicon-left hidden-md-down"><a id="btnLeftMenu" href=""><i class="icon ion-navicon-round"></i></a></div>
        <div class="navicon-left hidden-lg-up"><a id="btnLeftMenuMobile" href=""><i class="icon ion-navicon-round"></i></a></div>
        <div class="input-group hidden-xs-down wd-170 transition" style="display: none">
          <input id="searchbox" type="text" class="form-control" placeholder="Search">
          <span class="input-group-btn">
            <button class="btn btn-secondary" type="button"><i class="fas fa-search"></i></button>
          </span>
        </div><!-- input-group -->
      </div><!-- br-header-left -->
      <div class="br-header-right">
        <nav class="nav">
          <div class="dropdown" style="display: none;">
            <a href="" class="nav-link pd-x-7 pos-relative" data-toggle="dropdown">
              <i class="icon ion-ios-email-outline tx-24"></i>
              <!-- start: if statement -->
              <span class="square-8 bg-danger pos-absolute t-15 r-0 rounded-circle"></span>
              <!-- end: if statement -->
            </a>
            <div class="dropdown-menu dropdown-menu-header">
              <div class="dropdown-menu-label">
                <label>Messages</label>
                <a href="">+ Add New Message</a>
              </div><!-- d-flex -->

              <div class="media-list">
                <!-- loop starts here -->
                <a href="" class="media-list-link">
                  <div class="media">
                    <img src="https://via.placeholder.com/500" alt="">
                    <div class="media-body">
                      <div>
                        <p>Donna Seay</p>
                        <span>2 minutes ago</span>
                      </div><!-- d-flex -->
                      <p>A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring.</p>
                    </div>
                  </div><!-- media -->
                </a>
                <!-- loop ends here -->
                <a href="" class="media-list-link read">
                  <div class="media">
                    <img src="https://via.placeholder.com/500" alt="">
                    <div class="media-body">
                      <div>
                        <p>Samantha Francis</p>
                        <span>3 hours ago</span>
                      </div><!-- d-flex -->
                      <p>My entire soul, like these sweet mornings of spring.</p>
                    </div>
                  </div><!-- media -->
                </a>
                <a href="" class="media-list-link read">
                  <div class="media">
                    <img src="https://via.placeholder.com/500" alt="">
                    <div class="media-body">
                      <div>
                        <p>Robert Walker</p>
                        <span>5 hours ago</span>
                      </div><!-- d-flex -->
                      <p>I should be incapable of drawing a single stroke at the present moment...</p>
                    </div>
                  </div><!-- media -->
                </a>
                <a href="" class="media-list-link read">
                  <div class="media">
                    <img src="https://via.placeholder.com/500" alt="">
                    <div class="media-body">
                      <div>
                        <p>Larry Smith</p>
                        <span>Yesterday</span>
                      </div><!-- d-flex -->
                      <p>When, while the lovely valley teems with vapour around me, and the meridian sun strikes...</p>
                    </div>
                  </div><!-- media -->
                </a>
                <div class="dropdown-footer">
                  <a href=""><i class="fas fa-angle-down"></i> Show All Messages</a>
                </div>
              </div><!-- media-list -->
            </div><!-- dropdown-menu -->
          </div><!-- dropdown -->
          <div class="dropdown" style="display: none;">
            <a href="" class="nav-link pd-x-7 pos-relative" data-toggle="dropdown">
              <i class="icon ion-ios-bell-outline tx-24"></i>
              <!-- start: if statement -->
              <span class="square-8 bg-danger pos-absolute t-15 r-5 rounded-circle"></span>
              <!-- end: if statement -->
            </a>
            <div class="dropdown-menu dropdown-menu-header">
              <div class="dropdown-menu-label">
                <label>Notifications</label>
                <a href="">Mark All as Read</a>
              </div><!-- d-flex -->

              <div class="media-list">
                <!-- loop starts here -->
                <a href="" class="media-list-link read">
                  <div class="media">
                    <img src="https://via.placeholder.com/500" alt="">
                    <div class="media-body">
                      <p class="noti-text"><strong>Suzzeth Bungaos</strong> tagged you and 18 others in a post.</p>
                      <span>October 03, 2017 8:45am</span>
                    </div>
                  </div><!-- media -->
                </a>
                <!-- loop ends here -->
                <a href="" class="media-list-link read">
                  <div class="media">
                    <img src="https://via.placeholder.com/500" alt="">
                    <div class="media-body">
                      <p class="noti-text"><strong>Mellisa Brown</strong> appreciated your work <strong>The Social Network</strong></p>
                      <span>October 02, 2017 12:44am</span>
                    </div>
                  </div><!-- media -->
                </a>
                <a href="" class="media-list-link read">
                  <div class="media">
                    <img src="https://via.placeholder.com/500" alt="">
                    <div class="media-body">
                      <p class="noti-text">20+ new items added are for sale in your <strong>Sale Group</strong></p>
                      <span>October 01, 2017 10:20pm</span>
                    </div>
                  </div><!-- media -->
                </a>
                <a href="" class="media-list-link read">
                  <div class="media">
                    <img src="https://via.placeholder.com/500" alt="">
                    <div class="media-body">
                      <p class="noti-text"><strong>Julius Erving</strong> wants to connect with you on your conversation with <strong>Ronnie Mara</strong></p>
                      <span>October 01, 2017 6:08pm</span>
                    </div>
                  </div><!-- media -->
                </a>
                <div class="dropdown-footer">
                  <a href=""><i class="fas fa-angle-down"></i> Show All Notifications</a>
                </div>
              </div><!-- media-list -->
            </div><!-- dropdown-menu -->
          </div><!-- dropdown -->
          <div class="dropdown">
            <a href="" class="nav-link nav-link-profile" data-toggle="dropdown">
              <span class="logged-name hidden-md-down">{{ $infoAdmin->adm_name }}</span>
              <img src="https://via.placeholder.com/500" class="wd-32 rounded-circle" alt="">
              <span class="square-10 bg-success"></span>
            </a>

            <div class="dropdown-menu dropdown-menu-header wd-250">
              <div class="tx-center">
                <a href=""><img src="https://via.placeholder.com/500" class="wd-80 rounded-circle" alt=""></a>
                <h6 class="logged-fullname">{{ $infoAdmin->adm_name }}</h6>
              </div>
              <div class="tx-center" style="display: none;">
                <span class="profile-earning-label">Earnings After Taxes</span>
                <h3 class="profile-earning-amount">$13,230 <i class="icon ion-ios-arrow-thin-up tx-success"></i></h3>
                <span class="profile-earning-text">Based on list price.</span>
              </div>
              <ul class="list-unstyled user-profile-nav">
                <li><a href="{{route('admin.profile.changepass')}}"><i class="icon ion-ios-person"></i> Đổi mật khẩu</a></li>
                <li><a href="{{route('auth_admin.do_logout')}}"><i class="icon ion-power"></i>Đăng xuất</a></li>
              </ul>
            </div><!-- dropdown-menu -->
          </div><!-- dropdown -->
        </nav>
        <div class="navicon-right" style="display: none;">
          <a id="btnRightMenu" href="" class="pos-relative">
            <i class="icon ion-ios-chatboxes-outline"></i>
            <!-- start: if statement -->
            <span class="square-8 bg-danger pos-absolute t-10 r--5 rounded-circle"></span>
            <!-- end: if statement -->
          </a>
        </div><!-- navicon-right -->
      </div><!-- br-header-right -->
    </div>

resources/views/admin/login.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="{{ asset('assets/admin/lib/@fortawesome/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
  <link href="{{ asset('assets/admin/lib/ionicons/css/ionicons.min.css') }}" rel="stylesheet" type="text/css">
  <link href="{{ asset('assets/admin/css/bracket.css') }}" rel="stylesheet" type="text/css">
  <link href="{{ asset('assets/admin/css/jquery.growl.css') }}" rel="stylesheet" type="text/css">
    <style type="text/css">
        .login_error{
            list-style: none;
        }
    </style>
</head>
<body class="hold-transition login-page">

	<div class="d-flex align-items-center justify-content-center bg-br-primary ht-100v">
		<div class="login-wrapper wd-300 wd-xs-350 pd-25 pd-xs-40 bg-white rounded shadow-base">
			<div class="signin-logo tx-center tx-28 tx-bold tx-inverse"><span class="tx-normal"></span> ADMIN <span class="tx-info">VBCWE</span> <span class="tx-normal"></span></div>
            @if ($errors->any())
                <ul class="alert alert-danger login_error">
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            @endif
            <form action="{{route('auth_admin.login')}}" method="post" class="mg-t-20">
        		@csrf
				<div class="form-group">
					<input type="text" name="username"  class="form-control" placeholder="Enter your username">
				</div><!-- form-group -->
				<div class="form-group">
					<input type="password" name="password" class="form-control" placeholder="Enter your Password">
					<a href="" class="tx-info tx-12 d-block mg-t-10" style="display: none !important;">Quên mật khẩu?</a>
				</div><!-- form-group -->
				<input type="hidden" name="action" value="login">
				<button type="submit" class="btn btn-info btn-block mg-t-20">Sign In</button>
			</form>
		</div><!-- login-wrapper -->
	</div><!-- d-flex -->

<!-- /.login-box -->
<script language="javascript" src="{{ asset('assets/admin/lib/jquery/jquery.min.js') }}"></script>
<script language="javascript" src="{{ asset('assets/admin/lib/jquery-ui/ui/widgets/datepicker.js') }}"></script>
<script language="javascript" src="{{ asset('assets/admin/lib/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script language="javascript" src="{{ asset('assets/admin/js/jquery.growl.js') }}"></script>


@include("admin.flash-message")

</body>
</html>

resources/views/admin/sidebar.blade.php
<?php $nameRouteCurrent = Route::currentRouteName();?>
<div class="br-sideleft sideleft-scrollbar ps ps--active-y">
      <ul class="br-sideleft-menu mg-t-20">
      	<li class="br-menu-item">
          <a href="{{ route('admin.dashboard.index') }}" class="br-menu-link {{ (request()->is('admin/dashboard*')) ? 'active' : '' }}">
            <i class="menu-item-icon icon ion-ios-home-outline tx-24"></i>
            <span class="menu-item-label">Dashboard</span>
          </a><!-- br-menu-link -->
        </li><!-- br-menu-item -->
		@isset($menuAdmin)
			@foreach ($menuAdmin as $key => $menu)
				<li class="br-menu-item">
	          		<a href="#" class="br-menu-link @if($menu['sub'])  with-sub @endif {{ (request()->is('admin/' . $menu['info']['prefix'] . '*')) ? 'active show-sub' : '' }}">
		          		<i class="menu-item-icon icon {{ $menu['info']['icon'] }} tx-20"></i>
		            	<span class="menu-item-label">{{ $menu['info']['label'] }}</span>
	            	</a>
	            	@if($menu['sub'])
						<ul class="br-menu-sub" style="{{ (request()->is('user/' . $menu['info']['prefix'] . '*')) ? 'display: block;' : '' }}" >
							@foreach ($menu['sub'] as $sub)
								@if($sub['is_menu'] == 1)
									<li class="sub-item">
						            	<a href="{{ route($sub['route']) }}" class="sub-link {{ ($nameRouteCurrent == $sub['route']) ? 'active' : '' }} ">{{ $sub['label'] }}</a>
						        	</li>
					        	@endif
							@endforeach
						</ul>
	            	@endif
	            </li>
			@endforeach
		@endisset
      </ul><!-- br-sideleft-menu -->
      <br>
    <div class="ps__rail-x" style="left: 0px; top: 0px;"><div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps__rail-y" style="top: 0px; height: 575px; right: 0px;"><div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 369px;"></div></div></div>
<!-- Main Sidebar Container -->